config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}

  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord

  before_save{self.email = email.downcase}

  has_many :articles, dependent: :destroy
  has_secure_password

  validates :username, presence: true,
                      uniqueness: {case_sensitive: false},
                      length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                  uniqueness: {case_sensitive: false},
                  format: {with: VALID_EMAIL_REGEX},
                  length: {maximum: 105}

  validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? #Disponible en vistas

  def current_user #Disponible en controladores
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #Si el valor ya existe no lo asigna de nuevo
  end

  def logged_in?
    !!current_user #Se convierte en un booleano
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_article_category, only: [:destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    #binding.break
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 6)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created succesfully."
      redirect_to @article #redirect_to article_path(@article)
    else
      render 'new', status: :unprocessable_entity
    end
    #render plain: @article.inspect #params[:article]
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated succesfully."
      redirect_to @article #redirect_to article_path(@article)
    else
      render 'edit', status: :unprocessable_entity
    end
    #render plain: @article.inspect #params[:article]
  end

  def destroy
    @article.destroy
    @article_category.destroy_all
    flash[:notice] = "Article was deleted succesfully."
    redirect_to articles_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_article_category
    @article_category = ArticleCategory.where(article_id: params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    unless current_user == @article.user || current_user.admin?
      flash[:alert] = "You can only edit or delete your own articles"
      redirect_to @article, status: :see_other
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:edit, :show, :update, :destroy]
  before_action :require_admin, except: [:index, :show]

  def index
    @category = Category.paginate(page: params[:page], per_page: 15)
  end

  def new
    @category = Category.new
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:notice] = "The category was successfully updated"
      redirect_to categories_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 15)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "The category was succesfully created"
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path, status: :see_other
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    #binding.break
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] =  "Wrong login information"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 6)

  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 6)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    #binding.break
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      session[:user_id] = @user.id
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:warning] = "User and all associated articles successfully deleted"
    redirect_to articles_path, status: :see_other
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    unless current_user == @user || current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user, status: :see_other
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options ={size:80, class:"rounded mx-auto d-block shadow my-2"})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: options[:class])
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="row justify-content-center">
  <% obj.each do |article| %>
    <div class="col-lg-5 col-11 gx-5 p-3">
      <div class="card text-center shadow rounded">
        <div class="card-header fst-italic text-muted">
          <div class="m-1">
            <% if article.categories.any? %>
              <%= render article.categories %>
            <% else %>
              No categories
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
          <p class="card-text"><%= truncate(article.description,length:100) %></p>
          <div class="row justify-content-center">
            <%= link_to 'Show', article_path(article), class: "btn btn-outline-primary col-3 mx-sm-1 mx-2"%>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info col-3 mx-sm-1 mx-2"%>
              <%= link_to 'Delete', article_path(article),  data: { "turbo-method": :delete, "turbo-confirm": "Are you sure of deleting #{article.title} by #{article.user.username}?"}, class: "btn btn-outline-danger col-3 mx-sm-1 mx-2"%>
            <% end %>
          </div>
        </div>
        <div class="card-footer text-muted">
          <small>Created by <%= link_to article.user.username, user_path(article.user), class: "fw-bold"%> <%= time_ago_in_words(article.created_at)%> ago, edited <%= time_ago_in_words(article.updated_at)%> ago</small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <%= render "shared/errors", obj: @article %>
  <%= form_with(model: @article, local: true, class:"my-5 row") do |f| %>
    <div class="mb-3 row">
      <div class="col-sm-2">
        <%= f.label :title, class: "col-form-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2">
        <%= f.label :description, class: "col-form-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2">
        <%= f.label :category, class: "col-form-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.collection_check_boxes :category_ids, Category.order(:name), :id, :name do |check| %>
          <%= check.check_box class: "btn-check" %>
          <%= check.label class:"btn btn-small btn-outline-primary m-1"%>
        <% end %>
        <%#= f.collection_select :category_id, Category.order(:name), :id, :name, {prompt: "Hola"}, {multiple: true, class: "form-select"} %>
      </div>
    </div>
    <div class="d-flex justify-content-end px-4">
      <%= link_to 'Back', articles_path, class: "btn btn-outline-secondary mx-2" %>
      <%= f.submit( @article.new_record? ? "Create" : "Update", class: "btn btn-primary mx-2", data: {turbo: "false"}) %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<% content_for :title, "Edit Article" %>

<h3>Edit article</h3>
<%= render 'form' %>

app/views/articles/index.html.erb
<% content_for :title, "Articles list" %>
<div class="row justify-content-between mx-lg-0 mx-3 mb-3">
  <div class="col-6">
    <h3>Articles list</h3>
  </div>
  <div class="col-6">
    <%= link_to 'Create new article', new_article_path, class: "btn btn-sm btn-success float-end" if logged_in?%>
  </div>
</div>
<% if @articles.empty? %>
  <p class="mb-5 mx-5 mt-2 text-secondary">Nothing to show. <%= link_to "Create a new article.", new_article_path, class:"text-success" if logged_in? %></p>
<% else %>
  <div class="flickr_pagination my-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
  <%= render 'article', obj: @articles %>
  <div class="flickr_pagination my-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<% content_for :title, "New Article" %>

<h3>Create a new article</h3>
<%= render 'form' %>

app/views/articles/show.html.erb
<% content_for :title, "Show Article" %>

<h3><%= @article.title %></h3>
<div class="row justify-content-center">
  <div class="col-lg-6 col-10">
    <div class="card text-center shadow rounded mt-5">
      <div class="card-header fst-italic text-muted">
        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <div class="m-1">
          <% if @article.categories.any? %>
            <%= render @article.categories %>
          <% else %>
            No categories
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <div class="card-text text-start"><%= simple_format(@article.description, {}, wrapper_tag: "span") %></div>
        <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
          <div class="row justify-content-center mt-2">
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info col-3 mx-sm-1 m-1"%>
            <%= link_to 'Delete', article_path(@article), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure of deleting #{@article.title} by #{@article.user.username}?"}, class: "btn btn-outline-danger col-3 mx-sm-1 m-1" %>
          </div>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Created by <%= link_to @article.user.username, user_path(@article.user), class:"fw-bold" %> <%= time_ago_in_words(@article.created_at)%> ago, edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
      </div>
    </div>
  </div>
</div>
<br/>
<div class="row justify-content-end">
  <div class="col-4 col-sm-2">
    <%= link_to 'Back', articles_path, class: "btn btn-outline-secondary mx-2" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge bg-primary m-1"><%= link_to category.name, category_path(category)  %></span>

app/views/categories/_form.html.erb
<div class="container">
  <%= render "shared/errors", obj: @category %>
  <%= form_with(model: @category, local: true, class:"my-5 row") do |f| %>
    <div class="mb-3 row">
      <div class="col-md-3 col-xl-2">
        <%= f.label :name, "Category name", class: "col-form-label" %>
      </div>
      <div class="col-md-9 col-xl-10">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter a name" %>
      </div>
    </div>
    <div class="d-flex justify-content-end px-4">
      <%= link_to 'Back', categories_path, class: "btn btn-outline-secondary mx-2" %>
      <%= f.submit( @category.new_record? ? 'Create' : 'Update', class: "btn btn-primary mx-2", data: {turbo: "false"}) %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<% content_for :title, "Edit Category" %>

<h3>Edit category</h3>
<%= render 'form' %>

app/views/categories/index.html.erb
<% content_for :title, "Categories list" %>
<div class="row justify-content-between mx-lg-0 mx-3 mb-3">
  <div class="col-6">
    <h3>Categories list</h3>
  </div>
  <div class="col-6">
    <%= link_to 'Create new category', new_category_path, class: "btn btn-sm btn-success float-end" if logged_in? && current_user.admin?%>
  </div>
</div>
<% if @category.empty? %>
  <p class="mb-5 mx-5 mt-2 text-secondary">Nothing to show. <%= link_to "Create a new category.", new_category_path, class:"text-success" if logged_in? && current_user.admin?%></p>
<% else %>
  <div class="flickr_pagination my-3">
    <%= will_paginate @category, :container => false %>
    <div class="page_info">
      <%= page_entries_info @category %>
    </div>
  </div>
  <div class="row justify-content-center">
    <% @category.each do |category| %>
      <%= link_to category_path(category), class: "btn btn-outline-primary shadow col-lg-2 col-sm-5 col-10 gx-5 p-3 m-2" do %>
        <h5 class="card-title m-0"> <%= category.name %></h5>
        <small> <%= pluralize(category.articles.count, "article") %></small>
      <% end %>
    <% end %>
  </div>
  <div class="flickr_pagination my-3">
    <%= will_paginate @category, :container => false %>
    <div class="page_info">
      <%= page_entries_info @category %>
    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<% content_for :title, "New Category" %>

<h3>Create a new category</h3>
<%= render 'form' %>

app/views/categories/show.html.erb
<% content_for :title, "Show Category" %>
<div class="row">
  <div class="col-6">
    <h3><%= @category.name %> <small class="h6 text-muted">Category</small></h3>
  </div>
  <div class="col-6">
    <%= link_to 'Edit category', edit_category_path(@category), class: "btn btn-sm btn-outline-info float-end" if logged_in? && current_user.admin?%>
  </div>
</div>
<% if @articles.empty? %>
  <p class="m-5">No articles in this category.</p>
<% else %>
  <div class="flickr_pagination my-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
  <%= render 'articles/article', obj: @articles %>
  <div class="flickr_pagination my-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
<% end %>
<div class="row justify-content-end">
  <%= link_to 'Back', categories_path, class: "btn btn-outline-secondary mx-2 col-2 col-xl-1" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-4 w-100 bg-light" id='footer_bar'>
  <div class="container text-end">
    All rights reserved to <%= link_to "Jhonny Tiscareño Ramirez", "https://www.linkedin.com/in/jhonnytisram/" %>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <% case name %>
    <% when "alert" %>
      <% type = "danger" %>
    <% when "notice" %>
      <% type = "success" %>
    <% when "warning" %>
      <% type = "warning" %>
    <% when "info" %>
      <% type = "info" %>
    <% else %>
      <% type = "primary" %>
  <% end %>
  <div class="alert alert-<%= type %> mb-5 shadow alert-dismissible fade show" role="alert" style="height:3.5em">
    <p><%= msg %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light px-4" id="navigation_bar">
  <div class="container-fluid p-md-3 p-1">
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav my-2">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class:"nav-link" %>
        </li>
        <% if logged_in?%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "All articles", articles_path, class:"dropdown-item" %></li>
              <li><%= link_to "New article", new_article_path, class:"dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View categories", categories_path, class:"dropdown-item" %></li>
              <% if current_user.admin? %>
                <li><%= link_to "New category", new_category_path, class:"dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.admin? %>
                <span class="badge bg-danger mx-1">Admin</span>
              <% end %>
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %></li>
              <li><%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %></li>
              <li><%= link_to "Delete your profile", user_path(current_user), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure of deleting your profile?" + ("\n\n#{pluralize(current_user.articles.count, "article")} you created will also be deleted." unless current_user.articles.empty?).to_s}, class:"dropdown-item text-danger" %></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class:"nav-link", data: { "turbo-method": :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Categories", categories_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", signup_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title) + " - " unless yield(:title).blank?).to_s + "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= yield :head %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% unless content_for?(:container) %>
      <div class="container my-5">
    <% end %>
        <%= render 'layouts/messages' %>
        <%= yield %>
    <% unless content_for?(:container) %>
      </div>
    <% end %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title, "About" %>

<h3>About page</h3>
<p class="text-success mt-5">This is my first ruby project</p>

app/views/pages/home.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "home", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "home", "data-turbo-track": "reload", defer: true %>
<% end %>
<% content_for :title, "Home" %>
<% content_for :container, "false" %>
<body class="position-relative">
  <div class="container-fluid p-0">
    <div id="intro" class="vh-100" style="min-height: 700px">
      <div class="h-100" style="background-color: rgba(0,0,0,.8);">
        <div class="h-100 container px-md-5 px-3 text-light text-md-start text-center">
          <div class="row h-100 align-items-center">
            <div class="col-12">
              <h1>Alpha Blog</h1>
              <p class="lead">
                <%= link_to 'Articles list', articles_path %> |
                <%= link_to 'About', about_path %>
              </p>
              <hr class="my-5"/>
              <div class="row justify-content-md-start justify-content-center">
                <%= link_to 'Sign up!', signup_path, class: "btn btn-outline-light btn-lg col-lg-2 col-3 mx-2", role: "button" %>
                 <%= link_to 'Log in', login_path, class: "btn btn-outline-light btn-lg col-lg-2 col-3 mx-2", role: "button" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-warning shadow alert-dismissible fade show my-3" role="alert">
  <p><strong>The following errors prevented the <%= obj.class.name.downcase %> from being saved</strong></p>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/users/_user.html.erb
<div class="row justify-content-center">
  <% @users.each do |user| %>
    <div class="col-lg-4 col-md-5 col-11 gx-5 mb-5 p-1 p-sm-3">
      <div class="card text-center shadow rounded">
        <div class="card-body">
          <h5 class="card-title"><%= link_to user.username, user %></h5>
          <%= link_to gravatar_for(user, size: 200, class: "my-3 rounded mx-auto d-block shadow"), user %>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <div class="row justify-content-center">
            <%= link_to 'View profile', user, class: "btn btn-outline-primary col-xxl-5 col-md-10 col-5 m-1"%>
            <% if logged_in? %>
              <% if user == current_user  %>
                <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info col-xxl-5 col-md-10 col-5 m-1"%>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to 'Delete user', user_path(user), data: {"turbo-method": :delete, "turbo-confirm": "Are you sure of deleting #{user.username}?" + "\n\n#{pluralize(user.articles.count, "article")} will also be deleted."}, class: "btn btn-outline-danger col-xxl-5 col-md-10 col-5 m-1"%>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Edit username" %>

<h3>Edit your username</h3>
<%= render 'form' %>

app/views/users/new.html.erb
<% content_for :title, "Signup" %>

<h3>Signup for Alpha Blog</h3>
<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :title, @user.username + "'s profile" %>

<h3><%= @user.username + "'s profile" %></h3>
<%= gravatar_for @user, size: 200, class: "my-5 rounded mx-auto d-block shadow"%>
<% if logged_in? && @user == current_user %>
  <div class="text-center my-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info col-lg-3 mx-2" %>
    <%= link_to "Change profile image", "https://www.gravatar.com/", class: "btn btn-outline-info col-lg-3 mx-2" %>
  </div>
<% end %>
<h4 class="mb-3" >Articles</h4>
<% if @articles.empty? %>
  <p class="mb-5 mt-2">You haven't published any articles yet.</p>
<% else %>
  <div class="flickr_pagination my-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
  <%= render 'articles/article', obj: @articles %>
  <div class="flickr_pagination my-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
<% end %>